spring:
  application:
    # 应用名称
    name: redis-02-springboot
  redis:
    password: 154490984   # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    cluster:
      nodes: #这里上你Redis的各个端口号
        - 159.75.4.236:6379
        - 159.75.4.236:6380
        - 159.75.4.236:6381
    sentinel:
      master: mymaster
      nodes:
        - 159.75.4.236:26379
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

# 应用服务 WEB 访问端口
server:
  port: 8080

